import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import projectsRouter from "./projects";
import extractsRouter from "./extracts";
import statsRouter from "./stats";
import storageRouter from "./storage";
import auditRouter from "./audit";
import supportRouter from "./support";
import submittedExtractsRouter from "./submitted-extracts";
import adminRouter from "./admin";
import adminBackupRouter from "./admin-backup";
import hospitalStorageRouter from "./hospital-storage";
import adminSettingsRouter from "./admin-settings";
import exportRouter from "./export";
import remindRouter from "./remind";
import analyticsRouter from "./analytics";
import visitsRouter from "./visits";
import adminFoundationRouter from "./admin-foundation";
import adminNotifyRouter from "./admin-notify";
import adminJobPositionsRouter from "./admin-job-positions";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/users", authRouter);
router.use("/users", usersRouter);
router.use("/projects", projectsRouter);
router.use("/extracts", extractsRouter);
router.use("/stats", statsRouter);
router.use("/storage", storageRouter);
router.use("/audit", auditRouter);
router.use("/support", supportRouter);
router.use("/submitted-extracts", submittedExtractsRouter);
router.use("/admin", adminRouter);
router.use("/admin/backup", adminBackupRouter);
router.use("/admin/settings", adminSettingsRouter);
router.use("/export", exportRouter);
router.use("/remind", remindRouter);
router.use("/analytics", analyticsRouter);
router.use("/hospital-storage", hospitalStorageRouter);
router.use("/visits", visitsRouter);
router.use("/admin/foundation", adminFoundationRouter);
router.use("/admin/notify", adminNotifyRouter);
router.use("/admin/job-positions", adminJobPositionsRouter);

export default router;
