import { Router } from "express";
import { db, usersTable, systemSettingsTable } from "@workspace/db";
import { eq, sql, ne } from "drizzle-orm";
import { sendApprovalEmail, sendRejectionEmail } from "../lib/email";
import { logAudit } from "./audit";
import { requireAuth, clerk } from "../middleware/requireAuth";

const router = Router();
function getClerkDisplayName(clerkUser: any, email: string) {
  const metadataName =
    (clerkUser.publicMetadata?.name as string | undefined) ||
    (clerkUser.unsafeMetadata?.name as string | undefined) ||
    (clerkUser.publicMetadata?.fullName as string | undefined) ||
    (clerkUser.unsafeMetadata?.fullName as string | undefined);
  return metadataName?.trim() || clerkUser.fullName?.trim() || `${clerkUser.firstName ?? ""} ${clerkUser.lastName ?? ""}`.trim() || email.split("@")[0] || "مستخدم جديد";
}
const requireAdmin = async (req: any, res: any, next: any) => {
  try { const [user] = await db.select().from(usersTable).where(eq(usersTable.clerkId, req.clerkUserId)).limit(1); if (!user || user.role !== "admin") return res.status(403).json({ error: "Forbidden" }); req.currentUser = user; next(); }
  catch (err) { req.log.error({ err }, "requireAdmin failed"); res.status(500).json({ error: "Internal server error" }); }
};
const requireAdminOrSupervisor = async (req: any, res: any, next: any) => {
  try { const [user] = await db.select().from(usersTable).where(eq(usersTable.clerkId, req.clerkUserId)).limit(1); if (!user || !["admin", "supervisor"].includes(user.role)) return res.status(403).json({ error: "Forbidden" }); req.currentUser = user; next(); }
  catch (err) { req.log.error({ err }, "requireAdminOrSupervisor failed"); res.status(500).json({ error: "Internal server error" }); }
};
function auditWatchKey(supervisorId: number) { return `audit_watch_users_${supervisorId}`; }
async function readAuditWatchedUsers(supervisorId: number): Promise<number[]> { const [row] = await db.select().from(systemSettingsTable).where(eq(systemSettingsTable.key, auditWatchKey(supervisorId))).limit(1); if (!row?.value) return []; try { const parsed = JSON.parse(row.value); return Array.isArray(parsed) ? parsed.map(Number).filter(Boolean) : []; } catch { return []; } }
router.get("/:userId/audit-watch", requireAuth, requireAdmin, async (req: any, res) => { try { const supervisorId = Number(req.params.userId); const watchedUserIds = await readAuditWatchedUsers(supervisorId); return res.json({ supervisorId, watchedUserIds }); } catch (err) { req.log.error({ err }, "Failed to get audit watch users"); return res.status(500).json({ error: "Internal server error" }); } });
router.patch("/:userId/audit-watch", requireAuth, requireAdmin, async (req: any, res) => { try { const supervisorId = Number(req.params.userId); const ids = Array.isArray(req.body.watchedUserIds) ? req.body.watchedUserIds.map(Number).filter(Boolean).filter((id: number) => id !== supervisorId) : []; const uniqueIds = [...new Set(ids)]; const key = auditWatchKey(supervisorId); const value = JSON.stringify(uniqueIds); const [existing] = await db.select().from(systemSettingsTable).where(eq(systemSettingsTable.key, key)).limit(1); if (existing) await db.update(systemSettingsTable).set({ value, updatedAt: new Date(), updatedBy: req.currentUser.email }).where(eq(systemSettingsTable.key, key)); else await db.insert(systemSettingsTable).values({ key, value, updatedBy: req.currentUser.email }); const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; logAudit(req.currentUser.id, req.currentUser.email, req.currentUser.name, "تحديد مستخدمي المراقبة", `تم ربط مشرف رقم ${supervisorId} بمراقبة ${uniqueIds.length} مستخدم`, ip); return res.json({ supervisorId, watchedUserIds: uniqueIds }); } catch (err) { req.log.error({ err }, "Failed to save audit watch users"); return res.status(500).json({ error: "Internal server error" }); } });

router.get("/me", requireAuth, async (req: any, res) => { try { const clerkUserId = req.clerkUserId; let [user] = await db.select().from(usersTable).where(eq(usersTable.clerkId, clerkUserId)).limit(1); if (user?.status === "deleted") return res.status(403).json({ error: "ACCOUNT_DELETED", message: "هذا الحساب محذوف أو غير مفعل. يرجى التواصل مع الإدارة." }); if (user) return res.json(user); const clerkUser = await clerk.users.getUser(clerkUserId); const email = clerkUser.emailAddresses[0]?.emailAddress ?? ""; const name = getClerkDisplayName(clerkUser, email); const [byEmail] = await db.select().from(usersTable).where(eq(usersTable.email, email)).limit(1); if (byEmail?.status === "deleted") return res.status(403).json({ error: "ACCOUNT_DELETED", message: "هذا الحساب محذوف أو غير مفعل. يرجى التواصل مع الإدارة." }); if (byEmail) { const [updated] = await db.update(usersTable).set({ clerkId: clerkUserId, name: !byEmail.name || byEmail.name === "مستخدم جديد" ? name : byEmail.name }).where(eq(usersTable.id, byEmail.id)).returning(); return res.json(updated); } return res.status(404).json({ error: "User not found" }); } catch (err) { req.log.error({ err }, "Failed to get user"); return res.status(500).json({ error: "Internal server error" }); } });
router.post("/sync", requireAuth, async (req: any, res) => { try { const clerkUserId = req.clerkUserId; const { email, name, phone, company, hospital, jobTitle, contractNumber } = req.body; const clerkUser = await clerk.users.getUser(clerkUserId); const clerkEmail = clerkUser.emailAddresses[0]?.emailAddress ?? ""; const finalEmail = email || clerkEmail; const finalName = (name || "").trim() || getClerkDisplayName(clerkUser, finalEmail); let [existing] = await db.select().from(usersTable).where(eq(usersTable.clerkId, clerkUserId)).limit(1); if (!existing && finalEmail) [existing] = await db.select().from(usersTable).where(eq(usersTable.email, finalEmail)).limit(1); if (existing?.status === "deleted") return res.status(403).json({ error: "ACCOUNT_DELETED", message: "هذا الحساب محذوف أو غير مفعل. يرجى التواصل مع الإدارة." }); if (existing) { const [updated] = await db.update(usersTable).set({ clerkId: clerkUserId, email: finalEmail || existing.email, name: finalName || existing.name, phone: phone || existing.phone, company: company || existing.company, hospital: hospital || existing.hospital, jobTitle: jobTitle || existing.jobTitle, contractNumber: contractNumber || existing.contractNumber }).where(eq(usersTable.id, existing.id)).returning(); return res.json(updated); } const [created] = await db.insert(usersTable).values({ clerkId: clerkUserId, email: finalEmail, name: finalName, phone: phone || null, company: company || null, hospital: hospital || null, jobTitle: jobTitle || null, contractNumber: contractNumber || null, role: "user", status: "pending" }).returning(); return res.json(created); } catch (err) { req.log.error({ err }, "Failed to sync user"); return res.status(500).json({ error: "Internal server error" }); } });
router.patch("/me", requireAuth, async (req: any, res) => { try { const [user] = await db.select().from(usersTable).where(eq(usersTable.clerkId, req.clerkUserId)).limit(1); if (!user) return res.status(404).json({ error: "User not found" }); const { name, phone, jobTitle } = req.body; const updates: Record<string, any> = {}; if (name) updates.name = name; if (phone !== undefined) updates.phone = phone; if (jobTitle !== undefined) updates.jobTitle = jobTitle; const [updated] = await db.update(usersTable).set(updates).where(eq(usersTable.id, user.id)).returning(); return res.json(updated); } catch (err) { req.log.error({ err }, "Failed to update profile"); return res.status(500).json({ error: "Internal server error" }); } });
async function handleActivity(req: any, res: any) { try { const { page, event, details } = req.body; if (!page) return res.status(400).json({ error: "page required" }); let [existing] = await db.select().from(usersTable).where(eq(usersTable.clerkId, req.clerkUserId)).limit(1); if (!existing) { const clerkUser = await clerk.users.getUser(req.clerkUserId); const email = clerkUser.emailAddresses[0]?.emailAddress ?? ""; const name = getClerkDisplayName(clerkUser, email); [existing] = await db.insert(usersTable).values({ clerkId: req.clerkUserId, email, name, role: "user", status: "pending" }).returning(); } const [user] = await db.update(usersTable).set({ lastPage: page, lastPageAt: new Date() }).where(eq(usersTable.clerkId, req.clerkUserId)).returning(); if (event && user) { const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; logAudit(user.id, user.email, user.name ?? "", event, details || page, ip); } return res.json({ ok: true }); } catch (err) { req.log.error({ err }, "Failed to update activity"); return res.status(500).json({ error: "Internal server error" }); } }
router.patch("/me/activity", requireAuth, handleActivity); router.post("/me/activity", requireAuth, handleActivity);
router.patch("/me/login", requireAuth, async (req: any, res) => { try { const [existingUser] = await db.select().from(usersTable).where(eq(usersTable.clerkId, req.clerkUserId)).limit(1); if (!existingUser) return res.status(404).json({ error: "User not found" }); const now = new Date(); const lastLoginAt = existingUser.lastLoginAt ? new Date(existingUser.lastLoginAt) : null; const shouldLogLogin = !lastLoginAt || now.getTime() - lastLoginAt.getTime() > 30 * 60 * 1000; const [user] = await db.update(usersTable).set({ lastLoginAt: now }).where(eq(usersTable.id, existingUser.id)).returning(); if (shouldLogLogin) { const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; logAudit(user.id, user.email, user.name, "تسجيل دخول", undefined, ip); } return res.json({ ok: true }); } catch (err) { req.log.error({ err }, "Failed to update last login"); return res.status(500).json({ error: "Internal server error" }); } });
router.get("/", requireAuth, requireAdminOrSupervisor, async (req: any, res) => { try { const { status, page = 1, limit = 50 } = req.query; const offset = (Number(page) - 1) * Number(limit); let query = db.select().from(usersTable) as any; let countQuery = db.select({ count: sql<number>`count(*)` }).from(usersTable) as any; if (status) { query = query.where(eq(usersTable.status, status as any)); countQuery = countQuery.where(eq(usersTable.status, status as any)); } else { query = query.where(ne(usersTable.status, "deleted" as any)); countQuery = countQuery.where(ne(usersTable.status, "deleted" as any)); } const users = await query.limit(Number(limit)).offset(offset); const [{ count }] = await countQuery; return res.json({ users, total: Number(count), page: Number(page), limit: Number(limit) }); } catch (err) { req.log.error({ err }, "Failed to list users"); return res.status(500).json({ error: "Internal server error" }); } });
router.post("/:userId/approve", requireAuth, requireAdmin, async (req: any, res) => { try { const { userId } = req.params; const [user] = await db.update(usersTable).set({ status: "approved" }).where(eq(usersTable.id, Number(userId))).returning(); if (!user) return res.status(404).json({ error: "User not found" }); sendApprovalEmail(user.email, user.name).catch(() => {}); const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; logAudit(req.currentUser.id, req.currentUser.email, req.currentUser.name, "موافقة على مستخدم", `تمت الموافقة على ${user.name} (${user.email})`, ip); return res.json(user); } catch (err) { req.log.error({ err }, "Failed to approve user"); return res.status(500).json({ error: "Internal server error" }); } });
router.post("/:userId/reject", requireAuth, requireAdmin, async (req: any, res) => { try { const { userId } = req.params; const [user] = await db.update(usersTable).set({ status: "rejected" }).where(eq(usersTable.id, Number(userId))).returning(); if (!user) return res.status(404).json({ error: "User not found" }); sendRejectionEmail(user.email, user.name).catch(() => {}); const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; logAudit(req.currentUser.id, req.currentUser.email, req.currentUser.name, "رفض مستخدم", `تم رفض ${user.name} (${user.email})`, ip); return res.json(user); } catch (err) { req.log.error({ err }, "Failed to reject user"); return res.status(500).json({ error: "Internal server error" }); } });
router.patch("/:userId/role", requireAuth, requireAdmin, async (req: any, res) => { try { const { userId } = req.params; const { role, contractCompany } = req.body; if (!["admin", "supervisor", "contract_supervisor", "viewer", "user"].includes(role)) return res.status(400).json({ error: "Invalid role" }); const updates: Record<string, any> = { role }; if (role === "contract_supervisor") { if (!contractCompany) return res.status(400).json({ error: "contractCompany required for contract_supervisor" }); updates.contractCompany = contractCompany; } else updates.contractCompany = null; const [user] = await db.update(usersTable).set(updates).where(eq(usersTable.id, Number(userId))).returning(); if (!user) return res.status(404).json({ error: "User not found" }); const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; const roleAr = role === "admin" ? "مدير النظام" : role === "supervisor" ? "مشرف" : role === "contract_supervisor" ? `مشرف عقد (${contractCompany})` : "مستخدم عادي"; logAudit(req.currentUser.id, req.currentUser.email, req.currentUser.name, "تغيير صلاحية", `تغيير دور ${user.name} إلى ${roleAr}`, ip); return res.json(user); } catch (err) { req.log.error({ err }, "Failed to change role"); return res.status(500).json({ error: "Internal server error" }); } });
router.get("/company/:company", requireAuth, async (req: any, res) => { try { const role = req.currentUser.role; const { company } = req.params; if (role !== "admin" && role !== "supervisor") { if (role !== "contract_supervisor" || req.currentUser.contractCompany !== company) return res.status(403).json({ error: "Forbidden" }); } const { and, inArray } = await import("drizzle-orm"); const COMPANY_SITES: Record<string, string[]> = { "بيت_العرب": ["مستشفى يدمة العام", "مستشفى حبونا العام", "مستشفى بدر الجنوب العام", "مستشفى الولادة والأطفال", "مستشفى نجران العام القديم وسكن الممرضات الخارجي", "المكاتب الإدارية والمرافق الصحية", "صيانة وإصلاح السيارات والعيادات المتنقلة"], "سراكو": ["مستشفى نجران العام الجديد", "مركز طب الأسنان التخصصي", "مجمع الأمل للصحة النفسية", "مستشفى ثار العام", "مستشفى خباش العام", "المراكز الصحية", "مستشفى الملك خالد", "مركز الأمير سلطان", "مستشفى شروره العام"] }; const sites = COMPANY_SITES[company]; if (!sites) return res.status(400).json({ error: "Unknown company" }); const users = await db.select().from(usersTable).where(and(inArray(usersTable.hospital, sites), ne(usersTable.status, "deleted" as any))); return res.json({ users, total: users.length }); } catch (err) { req.log.error({ err }, "Failed to list company users"); return res.status(500).json({ error: "Internal server error" }); } });
router.post("/:userId/deactivate", requireAuth, requireAdmin, async (req: any, res) => { try { const { userId } = req.params; const [user] = await db.update(usersTable).set({ status: "rejected" }).where(eq(usersTable.id, Number(userId))).returning(); if (!user) return res.status(404).json({ error: "User not found" }); const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; logAudit(req.currentUser.id, req.currentUser.email, req.currentUser.name, "تعطيل حساب", `تم تعطيل حساب ${user.name} (${user.email})`, ip); return res.json(user); } catch (err) { req.log.error({ err }, "Failed to deactivate user"); return res.status(500).json({ error: "Internal server error" }); } });
router.patch("/:userId/modules", requireAuth, requireAdmin, async (req: any, res) => { try { const { userId } = req.params; const { modules } = req.body; const allowedModules = modules === null ? null : JSON.stringify(modules); const [user] = await db.update(usersTable).set({ allowedModules }).where(eq(usersTable.id, Number(userId))).returning(); if (!user) return res.status(404).json({ error: "User not found" }); const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; logAudit(req.currentUser.id, req.currentUser.email, req.currentUser.name, "تعديل وحدات المستخدم", `وحدات ${user.name}: ${allowedModules || "الكل"}`, ip); return res.json(user); } catch (err) { req.log.error({ err }, "Failed to update modules"); return res.status(500).json({ error: "Internal server error" }); } });
router.patch("/me/hospital", requireAuth, async (req: any, res) => { try { const [user] = await db.select().from(usersTable).where(eq(usersTable.clerkId, req.clerkUserId)).limit(1); if (!user) return res.status(404).json({ error: "User not found" }); const { hospital } = req.body; if (!hospital) return res.status(400).json({ error: "hospital required" }); const allowed: string[] = user.hospitals ? JSON.parse(user.hospitals) : (user.hospital ? [user.hospital] : []); if (!allowed.includes(hospital) && user.role !== "admin") return res.status(403).json({ error: "Not allowed for this hospital" }); const [updated] = await db.update(usersTable).set({ hospital }).where(eq(usersTable.id, user.id)).returning(); return res.json(updated); } catch (err) { req.log.error({ err }, "Failed to switch hospital"); return res.status(500).json({ error: "Internal server error" }); } });
router.patch("/:userId/hospital", requireAuth, requireAdmin, async (req: any, res) => { try { const { userId } = req.params; const { hospital } = req.body; const [user] = await db.update(usersTable).set({ hospital: hospital || null }).where(eq(usersTable.id, Number(userId))).returning(); if (!user) return res.status(404).json({ error: "User not found" }); const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; logAudit(req.currentUser.id, req.currentUser.email, req.currentUser.name, "تغيير مستشفى", `تغيير مستشفى ${user.name} إلى: ${hospital || "بدون مستشفى"}`, ip); return res.json(user); } catch (err) { req.log.error({ err }, "Failed to update hospital"); return res.status(500).json({ error: "Internal server error" }); } });
router.patch("/:userId/hospitals", requireAuth, requireAdmin, async (req: any, res) => { try { const { userId } = req.params; const { hospitals } = req.body as { hospitals: string[] }; if (!Array.isArray(hospitals)) return res.status(400).json({ error: "hospitals must be array" }); const hospitalsJson = hospitals.length > 0 ? JSON.stringify(hospitals) : null; const primary = hospitals[0] || null; const [user] = await db.update(usersTable).set({ hospitals: hospitalsJson, hospital: primary }).where(eq(usersTable.id, Number(userId))).returning(); if (!user) return res.status(404).json({ error: "User not found" }); const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; logAudit(req.currentUser.id, req.currentUser.email, req.currentUser.name, "تعيين مواقع متعددة", `مواقع ${user.name}: ${hospitals.join(" / ")}`, ip); return res.json(user); } catch (err) { req.log.error({ err }, "Failed to update hospitals"); return res.status(500).json({ error: "Internal server error" }); } });
router.delete("/:userId", requireAuth, requireAdmin, async (req: any, res) => { try { const { userId } = req.params; const numericId = Number(userId); if (isNaN(numericId)) return res.status(400).json({ error: "Invalid user ID" }); const [user] = await db.select().from(usersTable).where(eq(usersTable.id, numericId)).limit(1); if (!user) return res.status(404).json({ error: "User not found" }); if (user.clerkId === req.clerkUserId) return res.status(403).json({ error: "لا يمكنك حذف حسابك أنت" }); if (user.clerkId) { try { await clerk.users.deleteUser(user.clerkId); } catch (clerkErr: any) { req.log.warn({ clerkErr: clerkErr?.message, userId, clerkId: user.clerkId }, "Clerk delete failed — continuing with local soft delete"); } } const [updated] = await db.update(usersTable).set({ status: "deleted" as any }).where(eq(usersTable.id, numericId)).returning(); if (!updated) return res.status(404).json({ error: "User already deleted" }); const ip = req.headers["x-forwarded-for"]?.toString() || req.socket?.remoteAddress; logAudit(req.currentUser.id, req.currentUser.email, req.currentUser.name, "حذف مستخدم", `تم حذف ${user.name} (${user.email}) من شاشة المستخدمين وتعطيله من تسجيل الدخول`, ip); return res.json({ ok: true, deleted: user.name }); } catch (err: any) { req.log.error({ err: err?.message, stack: err?.stack }, "Failed to delete user"); return res.status(500).json({ error: "فشل حذف المستخدم", detail: err?.message }); } });
router.post("/:userId/activate", requireAuth, requireAdmin, async (req: any, res) => { try { const { userId } = req.params; const numericId = Number(userId); const [existing] = await db.select().from(usersTable).where(eq(usersTable.id, numericId)).limit(1); if (!existing) return res.status(404).json({ error: "User not found" }); if (existing.status === "deleted") return res.status(400).json({ error: "لا يمكن تفعيل مستخدم محذوف" }); const [user] = await db.update(usersTable).set({ status: "approved" }).where(eq(usersTable.id, numericId)).returning(); const ip = req.headers["x-forwarded-for"]?.toString() || req.socket.remoteAddress; logAudit(req.currentUser.id, req.currentUser.email, req.currentUser.name, "تفعيل حساب", `تم تفعيل حساب ${user.name} (${user.email})`, ip); return res.json(user); } catch (err) { req.log.error({ err }, "Failed to activate user"); return res.status(500).json({ error: "Internal server error" }); } });
export default router;